# Numpy (Numerical Python)
---
These are my personal notes that I tooke while I was sutuding Numpy (Chapter 2) from the book [Python Data Science Handbook: Essential Tools for Working with Data, VanderPlas, J. (2016)](https://jakevdp.github.io/PythonDataScienceHandbook/)


In [1]:
import numpy as np
np.__version__

'1.19.3'

In [2]:
# np.<TAB>
# you can use this code to display all the contents of the numpy namespace, 

In [27]:
'''
np?

'''

'\nnp?\n\n'

In [4]:
result = 0
for i in range(100):
    result += i
    print(result)

0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950


In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L)

list

In [7]:
type(L[0])

int

In [8]:
L2 = [str(i) for i in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(L2)

list

In [10]:
type(L2[0])

str

In [11]:
L3 = [True, '2', 3.7, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [12]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np_array = np.array = [1, 4, 2, 5, 3]
np_array

[1, 4, 2, 5, 3]

In [14]:
[type(i) for i in np_array]

[int, int, int, int, int]

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point)

In [15]:
np_array_2 = np.array = [1.1, 2, 3, 5, 44]
np_array_2

[1.1, 2, 3, 5, 44]

In [16]:
[type(i) for i in np_array_2]

[float, int, int, int, int]

## The Basics of NumPy Arrays


In [17]:
# Create a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
a = np.random.rand(7)
a

array([0.53671937, 0.02804371, 0.05055308, 0.46142454, 0.09080016,
       0.34758771, 0.93072488])

In [19]:
print('a ndim:', a.ndim)
print('a nshape:', a.shape)
print('a size:', a.size)

a ndim: 1
a nshape: (7,)
a size: 7


In [20]:
b = np.random.rand(2,3)
b

array([[0.2487724 , 0.23909309, 0.13003595],
       [0.06085132, 0.50271253, 0.1453623 ]])

In [21]:
print('b ndim:', b.ndim)
print('b nshape:', b.shape)
print('b size:', b.size)

b ndim: 2
b nshape: (2, 3)
b size: 6


In [22]:
c = np.random.rand(2,3,5)
c

array([[[0.46376234, 0.69882448, 0.42211574, 0.49418376, 0.3010968 ],
        [0.11178378, 0.144491  , 0.72516569, 0.2828084 , 0.44975112],
        [0.06886401, 0.64857629, 0.53084678, 0.51356136, 0.55225466]],

       [[0.25847022, 0.19739738, 0.81025332, 0.20793028, 0.0961544 ],
        [0.40932458, 0.66390535, 0.02152449, 0.0751948 , 0.87987183],
        [0.60371996, 0.3611118 , 0.06613916, 0.37800625, 0.10666707]]])

In [23]:
print('c ndim:', c.ndim)
print('c nshape:', c.shape)
print('c size:', c.size)

c ndim: 3
c nshape: (2, 3, 5)
c size: 30


In [24]:
print('data type', a.dtype)

data type float64


In [25]:
print('a size:', a.itemsize, 'bytes')
print('b size:', b.itemsize, 'bytes')
print('c size:', c.size, 'bytes')

a size: 8 bytes
b size: 8 bytes
c size: 30 bytes
